### ISSUE TITLE
Why does aresponses stop the event loop?

### ISSUE THREAD

**Issue by Wim-De-Clercq** [CircleUp/aresponses#46]
As far as i can tell, aresponese does not create new event loops. It just uses loops that something else (pytest asyncio libraries, or the user themselves) created.

If you didn't start the loop, you shouldn't stop the loop. This is causing 
```
RuntimeError: Event loop stopped before Future completed.
```
which shouldn't exist because aresponses can't possibly know what the loop it is using is used for elsewhere.

What purpose does this `self._loop.stop()` serve? Everything seems to run more easily without it.
https://github.com/CircleUp/aresponses/blob/b21796733d5c230e792384b4ce2055df886e987a/aresponses/main.py#L107
I think this is the reason you have issues with `pytest-aiohttp` as well (I'm not using that).

**Comment by brycedrennan** [comment]
The purpose is to immediately stop the test since some failure case has occurred.  (As opposed to letting the test continue to run even though we know it has failed).

But yeah it was kind of annoying so proposed version 2.0 works differently.   Please provide feedback here: https://github.com/CircleUp/aresponses/pull/45
